### ISSUE TITLE
QR Code Scanner not working

### ISSUE THREAD

**Issue by pradeep-orbi** [khaled-qasem/MLBarcodeScanner#4]
Tried running the code from this repo. I'm just getting camera preview on the screen. ImageAnalyser and QR Code scanner are not working.

**Comment by khaled-qasem** [comment]
@pradeep-orbi  Can you send more details, device, os and api?
and logs please?

**Comment by pradeep-orbi** [comment]
device : Xiaomi MIA1
os :  Stock Android
api : Android 9 Pie

**Comment by khaled-qasem** [comment]
@pradeep-orbi 
This's just a basic Barcode scanner using Google ML Kit and Jetpack CameraX. There's no ui items on the UI. 
It will log barcode urls in the logcat. 
If there's a specific QR code you can't read, then it's an issue with Google ML Kit itself and we need to open an issue there with the attached code! 

The code reviewed and tested again, nothing to change in this sample. 
I'll close this issue!

Thanks,

**Comment by kpradeepkumarreddy** [comment]
> @pradeep-orbi This's just a basic Barcode scanner using Google ML Kit and Jetpack CameraX. There's no ui items on the UI. It will log barcode urls in the logcat. If there's a specific QR code you can't read, then it's an issue with Google ML Kit itself and we need to open an issue there with the attached code!
> 
> The code reviewed and tested again, nothing to change in this sample. I'll close this issue!
> 
> Thanks,

So, i should check the QR code url in the logcat ? I did not know that. I was expecting that the url will be shown on the UI itself after successful scan.

**Comment by khaled-qasem** [comment]
> > @pradeep-orbi This's just a basic Barcode scanner using Google ML Kit and Jetpack CameraX. There's no ui items on the UI. It will log barcode urls in the logcat. If there's a specific QR code you can't read, then it's an issue with Google ML Kit itself and we need to open an issue there with the attached code!
> > The code reviewed and tested again, nothing to change in this sample. I'll close this issue!
> > Thanks,
> 
> So, i should check the QR code url in the logcat ? I did not know that. I was expecting that the url will be shown on the UI itself after successful scan.

Exactly 👍 
Yes in Logcat only for code simplicity!
